# -*- coding: utf-8 -*-
"""Copie de visualisationdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvYNEbqNtiemHAMr9AgNoFf_FNMP8IMz

ecrire un programme por viualisation des données
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('/content/AAPL.csv')

# Display the first 5 rows of the DataFrame
print('Aperçu des données :')
display(df.head())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the cars dataset
df_cars = pd.read_csv('/content/cars.csv')

# Display the first 5 rows of the DataFrame
print('Aperçu des données du fichier cars.csv :')
display(df_cars.head())

"""Pour comprendre la structure des données et les types de colonnes, affichons les informations générales du DataFrame."""

# Check data types and non-null values
print('\nInformations sur les types de données :')
print(df_cars.info())

"""Visualisons maintenant la distribution de la consommation de carburant (MPG) à l'aide d'un histogramme.

Ensuite, visualisons le volume de trading au fil du temps.
"""

# Plotting the 'Volume' over time
plt.figure(figsize=(14, 7))
sns.lineplot(data=df, x=df.index, y='Volume', color='orange')
plt.title('AAPL Stock Trading Volume Over Time')
plt.xlabel('Date')
plt.ylabel('Volume')
plt.grid(True)
plt.show()

"""Visualisons maintenant la distribution des rendements quotidiens. Nous allons d'abord calculer les rendements quotidiens à partir du prix de clôture, puis tracer un histogramme pour voir comment ils sont répartis."""

# Calculate daily returns
df['Daily_Return'] = df['Close'].pct_change() * 100

# Plotting the histogram of daily returns
plt.figure(figsize=(12, 6))
sns.histplot(df['Daily_Return'].dropna(), bins=50, kde=True, color='skyblue')
plt.title('Distribution des Rendements Quotidiens de l\'Action AAPL')
plt.xlabel('Rendement Quotidien (%)')
plt.ylabel('Fréquence')
plt.grid(True)
plt.show()

"""Pour une visualisation, je vais d'abord vérifier les types de données et convertir la colonne 'Date' si nécessaire. Ensuite, je vais tracer le prix de clôture au fil du temps."""

# Check data types
print('\nTypes de données :')
print(df.info())

# Convert 'Date' column to datetime objects
df['Date'] = pd.to_datetime(df['Date'])

# Set 'Date' as index for time series plotting
df = df.set_index('Date')

# Plotting the 'Close' price over time
plt.figure(figsize=(14, 7))
sns.lineplot(data=df, x=df.index, y='Close')
plt.title('AAPL Stock Close Price Over Time')
plt.xlabel('Date')
plt.ylabel('Close Price (USD)')
plt.grid(True)
plt.show()